### PR TITLE
checkout pull request HEAD instead of merge commit

### PR DESCRIPTION
**Pull request by pavelzw**

### CODE REVIEW

**Comment by AdrianFreundQC** [comment]
I know we had that on our internal template, but later removed it again, but I don't remember the details.
Not having this makes GitHub run the CI against the pull request branch merged into main, instead of the pull request branch itself. Why do we not want that?

**Comment by pavelzw** [comment]
This can result in pretty nasty red CI as it isn't clear at all to the user that the CI isn't being executed on the commit you are using locally but on some merge with main.
Debugging this can take quite long if you don't know how GitHub behaves as it results in different behavior locally than in CI.

**Comment by 0xbe7a** [comment]
But the resulting failures would occur after the PR is merged into master on master, right?

**Comment by pavelzw** [comment]
Only if you don't activate "require branches to be up to date before merging"
image

**Comment by AdrianFreundQC** [comment]
> Only if you don't activate "require branches to be up to date before merging"

This isn't a default setting. Right?
This would be one more manual step people have to do and know about when creating a project.

I would agree that GitHub's default behavior can sometimes be confusing, but I would still prefer it over merging a green PR and then having CI fail on main.

**Comment by pavelzw** [comment]
Actually, another issue with this is that on other events such as `push` or `merge_group`, `github.event.pull_request.head.sha` might behave in unexpected / not documented / not directly understandable ways 🤔 it could be `''` or `null`. if it's `''`, everything should work as expected, though.

@borchero wdyt?

**Comment by borchero** [comment]
> "require branches to be up to date before merging"

While this makes CI more robust, I don't think this is a setting that should necessarily be used in practice as it hinders development velocity quite a bit :eyes:

> it could be '' or null. if it's '', everything should work as expected, though.

Afaik there's no notion of `null` in this context, you'll end up with an empty string

---

Tbh, I understand the theoretical discussion about the `ref` here but in 3 years of working with GH actions, I've not once had an issue with not specifying a `ref` when using `on: pull_request` triggers 🤷🏼‍♀️

**Comment by pavelzw** [comment]
Similar for me, it only happened once to me

**Pull request closed without merging**
